

title: Jason Zheng

### build settings ###
email: jzheng1995@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is Jasonâ€™s personal portfolio website with blogs, projects, and resume details.
theme: minima
url: https://jzheng1995.github.io
baseurl: ""

# add the following to _config.yml file
github_username: jzheng1995

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-optional-front-matter
- jekyll-feed